cfg/profile: move python cache to /tmp

diff --git a/cfg/profile b/cfg/profile
--- a/cfg/profile
+++ b/cfg/profile
@@ -1,17 +1,11 @@
-# ~/.profile: executed by the command interpreter for login shells.
-# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
-# exists.
-# see /usr/share/doc/bash/examples/startup-files for examples.
-# the files are located in the bash-doc package.
+# Ensure that /tmp is on a temporary file system.
+# (the assumption is that if it is mounted at least somewhere, probably it is on
+# a temporary file system).
+if ! mount | grep -q '\s/tmp'; then
+  echo "error: /tmp is not mounted on a temporary filesystem" >&2
+else
 
-# the default umask is set in /etc/profile; for setting the umask
-# for ssh logins, install and configure the libpam-umask package.
-#umask 022
+  # Hide Python cache to temporary directory.
+  export PYTHONPYCACHEPREFIX=/tmp/__pycache__
 
-# if running bash
-if [ -n "$BASH_VERSION" ]; then
-    # include .bashrc if it exists
-    if [ -f "$HOME/.bashrc" ]; then
-	. "$HOME/.bashrc"
-    fi
 fi
